---
name: Run renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - develop
      - main
jobs:
  renovate:
    name: Run renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@64257ea9bae8d8634eba1d545638c2cab62e69e6 # v39.2.1
        with:
          renovate-version: full
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
